name: Run Server

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  # Uncomment these if you want automatic triggering:
  # push:
  #   branches: [ main ]
  # schedule:
  #   - cron: '0 */12 * * *'  # Run every 12 hours

jobs:
  run-server:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true  # Important for your ONNX model

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Choose the version you need
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run server
    run: |
    python main.py &
    npx localtunnel --port 8000  # Assuming your server runs on port 8000